SELECT '304' as categoryId,'高危时段通话' as addComment,T.ZJHM as zjhm, T.TH_SJ as rzday, count(1) count FROM (
	-- 304.1，主叫
	SELECT ZJHM_LXDH.ZJHM, THJL_GWSD.BJ_LXDH AS LXDH, from_unixtime(unix_timestamp(THJL_GWSD.TH_SJ), 'yyyyMMdd') AS TH_SJ, 'ZJ' AS CALL_TYPE FROM (
		--304.0.1
		SELECT DISTINCT CASE WHEN SUBSTR(T.ZJ_LXDH, 1, 1) = '+' THEN TRANSLATE(SUBSTR(T.ZJ_LXDH, 4), '-', '') ELSE T.ZJ_LXDH END AS ZJ_LXDH, 
			CASE WHEN SUBSTR(T.BJ_LXDH, 1, 1) = '+' THEN TRANSLATE(SUBSTR(T.BJ_LXDH, 4), '-', '') ELSE T.BJ_LXDH END AS BJ_LXDH, T.TH_SJ 
		FROM HJK.ZHODS_GA_XJSIS_THJL T 
		WHERE LENGTH(T.ZJ_LXDH) IN (17, 11) AND LENGTH(T.BJ_LXDH) IN (17, 11) AND T.ZJ_LXDH <> T.BJ_LXDH 
			AND CAST(SUBSTR(T.TH_SJ, 11) AS TIMESTAMP) > CAST('00:00:00.000' AS TIMESTAMP) 
			AND CAST(SUBSTR(T.TH_SJ, 11) AS TIMESTAMP) < CAST('05:00:00.000' AS TIMESTAMP)
		--304.0.1
	) THJL_GWSD INNER JOIN (
		--304.0.2
		SELECT SYRK.ZJHM, SYRK.LXDH FROM HJK.GA_SYRK_SYRK SYRK WHERE LENGTH(SYRK.ZJHM) IN (15, 18) AND LENGTH(SYRK.LXDH) = 11 
		UNION 
		SELECT SBCBR.GMSFHM, SBCBR.LXDH FROM HJK.SH_SB_SBCBRXX SBCBR WHERE LENGTH(SBCBR.GMSFHM) IN (15, 18) AND LENGTH(SBCBR.LXDH) = 11 
		UNION 
		SELECT SBCBR.GMSFHM, SBCBR.DH_LXDH AS LXDH FROM HJK.SH_SB_SBCBRXX SBCBR WHERE LENGTH(SBCBR.GMSFHM) IN (15, 18) AND LENGTH(SBCBR.DH_LXDH) = 11
		--304.0.2
	) ZJHM_LXDH ON ZJHM_LXDH.LXDH = THJL_GWSD.ZJ_LXDH 
-- 304.1
	UNION 
-- 304.2，被叫
	SELECT ZJHM_LXDH.ZJHM, THJL_GWSD.ZJ_LXDH AS LXDH, from_unixtime(unix_timestamp(THJL_GWSD.TH_SJ), 'yyyyMMdd') AS TH_SJ, 'BJ' AS CALL_TYPE FROM (
		--304.0.1
		SELECT DISTINCT CASE WHEN SUBSTR(T.ZJ_LXDH, 1, 1) = '+' THEN TRANSLATE(SUBSTR(T.ZJ_LXDH, 4), '-', '') ELSE T.ZJ_LXDH END AS ZJ_LXDH, 
			CASE WHEN SUBSTR(T.BJ_LXDH, 1, 1) = '+' THEN TRANSLATE(SUBSTR(T.BJ_LXDH, 4), '-', '') ELSE T.BJ_LXDH END AS BJ_LXDH, T.TH_SJ 
		FROM HJK.ZHODS_GA_XJSIS_THJL T 
		WHERE LENGTH(T.ZJ_LXDH) IN (17, 11) AND LENGTH(T.BJ_LXDH) IN (17, 11) AND T.ZJ_LXDH <> T.BJ_LXDH 
			AND CAST(SUBSTR(T.TH_SJ, 11) AS TIMESTAMP) > CAST('00:00:00.000' AS TIMESTAMP) 
			AND CAST(SUBSTR(T.TH_SJ, 11) AS TIMESTAMP) < CAST('05:00:00.000' AS TIMESTAMP)
		--304.0.1
	) THJL_GWSD INNER JOIN (
		--304.0.2
		SELECT SYRK.ZJHM, SYRK.LXDH FROM HJK.GA_SYRK_SYRK SYRK WHERE LENGTH(SYRK.ZJHM) IN (15, 18) AND LENGTH(SYRK.LXDH) = 11 
		UNION 
		SELECT SBCBR.GMSFHM, SBCBR.LXDH FROM HJK.SH_SB_SBCBRXX SBCBR WHERE LENGTH(SBCBR.GMSFHM) IN (15, 18) AND LENGTH(SBCBR.LXDH) = 11 
		UNION 
		SELECT SBCBR.GMSFHM, SBCBR.DH_LXDH AS LXDH FROM HJK.SH_SB_SBCBRXX SBCBR WHERE LENGTH(SBCBR.GMSFHM) IN (15, 18) AND LENGTH(SBCBR.DH_LXDH) = 11
		--304.0.2
	) ZJHM_LXDH ON ZJHM_LXDH.LXDH = THJL_GWSD.BJ_LXDH
-- 304.2
) T INNER JOIN (
-- 304.3，人口
	SELECT SYRK.ZJHM, SYRK.LXDH FROM HJK.GA_SYRK_SYRK SYRK WHERE LENGTH(SYRK.ZJHM) IN (15, 18) AND LENGTH(SYRK.LXDH) = 11 
	UNION 
	SELECT SBCBR.GMSFHM, SBCBR.LXDH FROM HJK.SH_SB_SBCBRXX SBCBR WHERE LENGTH(SBCBR.GMSFHM) IN (15, 18) AND LENGTH(SBCBR.LXDH) = 11 
	UNION 
	SELECT SBCBR.GMSFHM, SBCBR.DH_LXDH AS LXDH FROM HJK.SH_SB_SBCBRXX SBCBR WHERE LENGTH(SBCBR.GMSFHM) IN (15, 18) AND LENGTH(SBCBR.DH_LXDH) = 11
-- 304.3
) ZJHM_LXDH ON ZJHM_LXDH.LXDH = T.LXDH WHERE (
-- 304.filter
	CASE LENGTH(T.ZJHM) 
	WHEN 18 THEN year(current_timestamp()) - CAST(SUBSTR(T.ZJHM, 7, 4) AS INT) 
	WHEN 15 THEN year(current_timestamp()) - (CAST(SUBSTR(T.ZJHM, 7, 2) AS INT) + 1900) 
	ELSE 0 END
-- 304.filter
) > 15 GROUP BY T.ZJHM, T.TH_SJ